management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,metrics
eureka:
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
spring:
  kafka:
    bootstrap-servers: host.docker.internal:9092