# customer-service.yml  (stored in Git)

server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: micro_user
    password: micro_pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: MICRO_USER
    database-platform: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    instances:
      customerServiceRetry:
        max-attempts: 3
        wait-duration: 2s

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
