# customer-service.yml  (stored in Git)

server:
  port: 8081

spring:
  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB  for local host only
    url: jdbc:oracle:thin:@//host.docker.internal:1521/ORCLPDB
    username: micro_user
    password: micro_pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: MICRO_USER
    database-platform: org.hibernate.dialect.OracleDialect

  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


