server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/inventory_db

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
