spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://host.docker.internal:8888"

  cloud:
    config:
      enabled: true

jwt:
  secret: testtesttesttesttesttesttesttest